### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by lapagept** [lukebranch/website_multi_image#6]
Traceback (most recent call last):
  File "/home/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/openerp/http.py", line 755, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/openerp/http.py", line 388, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/openerp/tools/convert.py", line 895, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/odoo/openerp/tools/convert.py", line 960, in convert_csv_import
    result, rows, warning_msg, dummy = registry[model].import_data(cr, uid, fields, datas,mode, module, noupdate, filename=fname_partial)
  File "/home/odoo/openerp/modules/registry.py", line 101, in __getitem__
    return self.models[model_name]
KeyError: u'website_multi_image'

**Comment by lapagept** [comment]
It works now. Download the file other place.

**Comment by lukebranch** [comment]
@Flooder666 ,

Thanks for the feedback. I've moved development for this module over to this repository to allow for easier collaboration:

https://github.com/OdooCommunityWidgets/website_multi_image/tree/master

I recommend using the 8.0 branch as i'll only push 'stable' changes to that branch. Please let me know if you have any other feedback or suggestions in regards to the module.
